// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2IBRwTqV1ZCsr0u4tISPwdQpfbOTGS1A',
    appId: '1:328188996700:android:634ffab9bee6f0cc878a99',
    messagingSenderId: '328188996700',
    projectId: 'talkease-285a9',
    storageBucket: 'talkease-285a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpgVROWKSxkZFSKpDpsOBUErvcy_GIMU',
    appId: '1:328188996700:ios:20afaeeb1875a0ae878a99',
    messagingSenderId: '328188996700',
    projectId: 'talkease-285a9',
    storageBucket: 'talkease-285a9.appspot.com',
    androidClientId: '328188996700-6988k90c1fsklch003nb9a2l3afnl2le.apps.googleusercontent.com',
    iosClientId: '328188996700-6k8o0tmqnq7se3nvsdi3lj9mn3on7jcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.seedHaven',
  );
}
